# TODO: need update
version: '3'

services:
  web:
    restart: always
    build: ./app
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: python -m gunicorn -b 0.0.0.0:8000 --workers=3 --max-requests 200 --reload --chdir=/app lrr.asgi:application -k uvicorn.workers.UvicornWorker

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "0.0.0.0:${NGINX_PORT}:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata: