# Generated by Django 4.2.15 on 2024-08-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование компетенции')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, verbose_name='Код направления подготовки')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование направления подготовки')),
                ('degree', models.CharField(choices=[('бакалавриат', 'бакалавриат'), ('специалитет', 'специалитет'), ('магистратура', 'магистратура'), ('аспирантура', 'аспирантура')], max_length=12, verbose_name='Уровень образования направления подготовки')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_contacts', models.TextField(blank=True, verbose_name='Контактные данные заявителя')),
                ('expert_access_details', models.TextField(blank=True, verbose_name='Режим доступа к ЭОР для эксперта')),
                ('type', models.CharField(choices=[('Полная', 'Полная'), ('Расширение области применения', 'Расширение области применения'), ('Отзыв Грифа МС', 'Отзыв Грифа МС')], max_length=29, verbose_name='Вид экспертизы ЭОР')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('state', models.CharField(choices=[('В процессе', 'В процессе'), ('Завершена (положительный результат)', 'Завершена (положительный результат)'), ('Завершена (отрицательный результат)', 'Завершена (отрицательный результат)')], default='В процессе', max_length=35, verbose_name='Состояние экспертизы')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('applicants', models.ManyToManyField(blank=True, to='users.person', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Экспертиза ЭОР',
                'verbose_name_plural': 'Экспертизы ЭОР',
            },
        ),
        migrations.CreateModel(
            name='ExpertReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование вида экспертного заключения')),
            ],
            options={
                'verbose_name': 'Вид экспертного заключения',
                'verbose_name_plural': 'Виды экспертного заключения',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование платформы')),
                ('url', models.URLField(verbose_name='URL платформы')),
                ('logo', models.ImageField(upload_to='platform_logo', verbose_name='Логотип платформы')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Код ЭОР')),
                ('type', models.CharField(choices=[('Электронный образовательный контент', 'Электронный образовательный контент'), ('Электронный учебный курс', 'Электронный учебный курс'), ('Онлайн-курс', 'Онлайн-курс')], max_length=35, verbose_name='Вид ЭОР')),
                ('title', models.TextField(verbose_name='Наименование ЭОР')),
                ('authors_text', models.TextField(verbose_name='Авторы ЭОР')),
                ('description', models.TextField(verbose_name='Аннотация ЭОР')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Пререквизиты ЭОР')),
                ('target', models.TextField(blank=True, verbose_name='Целевая аудитория ЭОР')),
                ('structure', models.TextField(blank=True, verbose_name='Перчень разделов (тем) ЭОР')),
                ('interactive', models.CharField(choices=[('Все интерактивные компоненты автоматизированы', 'Все интерактивные компоненты автоматизированы'), ('Некоторые интерактивные компоненты требуют участия преподавателя', 'Некоторые интерактивные компоненты требуют участия преподавателя'), ('Интерактивные компоненты отсутствуют', 'Интерактивные компоненты отсутствуют')], max_length=64, verbose_name='Наличие в ЭОР интерактивных компонентов и степень их автоматизации')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова')),
                ('results', models.TextField(blank=True, verbose_name='Результаты освоения ЭОР')),
                ('credits', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Трудоемкость освоения ЭОР')),
                ('requirements', models.TextField(blank=True, verbose_name='Минимальные системные требования')),
                ('contacts', models.TextField(blank=True, verbose_name='Контактные данные ответственного лица')),
                ('access_mode', models.CharField(choices=[('анонимный, открытый', 'анонимный, открытый'), ('анонимный, ограниченный (прямой ссылкой)', 'анонимный, ограниченный (прямой ссылкой)'), ('с аутентификацией пользователя, с открытой регистрацией', 'с аутентификацией пользователя, с открытой регистрацией'), ('с аутентификацией пользователя, с ограниченным доступом', 'с аутентификацией пользователя, с ограниченным доступом')], max_length=55, verbose_name='Режим доступа')),
                ('url', models.URLField(verbose_name='URL ЭОР')),
                ('resource_state', models.CharField(choices=[('Активный', 'Активный'), ('Архивный', 'Архивный')], default='Активный', max_length=8, verbose_name='Состояние ЭОР')),
                ('passport_state', models.CharField(choices=[('Утвержден', 'Утвержден'), ('Не утвержден', 'Не утвержден')], default='Не утвержден', max_length=12, verbose_name='Состояние Паспорта ЭОР')),
                ('stamp_state', models.CharField(choices=[('Имеется', 'Имеется'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=11, verbose_name='Гриф ЭОР')),
                ('stamp_text', models.TextField(blank=True, verbose_name='Текст Грифа ЭОР')),
                ('stamp_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоения Грифа ЭОР')),
                ('stamp_expiration', models.DateField(blank=True, null=True, verbose_name='Дата истечения срока действия Грифа ЭОР')),
                ('pub_state', models.CharField(choices=[('Является изданием', 'Является изданием'), ('Не является изданием', 'Не является изданием')], default='Не является изданием', max_length=20, verbose_name='Статус издания')),
                ('pub_imprint', models.TextField(blank=True, verbose_name='Выходные сведения издания')),
                ('pub_isbn', models.CharField(blank=True, max_length=17, verbose_name='ISBN издания')),
                ('pub_regnum', models.CharField(blank=True, max_length=10, verbose_name='Регистрационный номер издания')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания (не публикуются в Паспорте ЭОР)')),
                ('competences', models.ManyToManyField(blank=True, to='core.competence', verbose_name='Компетенции, в формировании которых участвует ЭОР')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='Подразделение-держатель ЭОР')),
                ('directions', models.ManyToManyField(blank=True, to='core.direction', verbose_name='Направления подготовки, для использования в рамках которых предназначен ЭОР')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.language', verbose_name='Язык контента ЭОР')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.platform', verbose_name='Платформа размещения ЭОР')),
            ],
            options={
                'verbose_name': 'ЭОР',
                'verbose_name_plural': 'ЭОРы',
            },
        ),
        migrations.CreateModel(
            name='Rightholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование правообладателя')),
            ],
            options={
                'verbose_name': 'Правообладатель',
                'verbose_name_plural': 'Правообладатели',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Ums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование УМС института')),
            ],
            options={
                'verbose_name': 'УМС института',
                'verbose_name_plural': 'УМС института',
            },
        ),
        migrations.CreateModel(
            name='ResourceStampApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(blank=True, max_length=7, verbose_name='Код модуля')),
                ('percentage', models.PositiveSmallIntegerField(verbose_name='Процент соответствия')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.direction', verbose_name='Направление подготовки')),
                ('expertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.expertise', verbose_name='Экспертиза ЭОР')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resource', verbose_name='ЭОР')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Соответвствие ЭОР направлению, дисциплине и модулю, установленное Грифом ЭОР',
                'verbose_name_plural': 'Соответвствия ЭОР направлениям, дисциплинам и модулям, установленные Грифом ЭОР',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='rightholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rightholder', verbose_name='Правообладатель ЭОР'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='core.subject', verbose_name='Дисциплины (модули), для использования в рамках которых предназначен ЭОР'),
        ),
        migrations.CreateModel(
            name='ExpertReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_contacts', models.TextField(blank=True, verbose_name='Контактные данные эксперта')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports', verbose_name='Файл экспертного заключения в PDF')),
                ('report_doc', models.FileField(blank=True, null=True, upload_to='reports', verbose_name='Файл экспертного заключения в DOC')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.person', verbose_name='Эксперт')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expertise', verbose_name='Экспертиза ЭОР')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expertreporttype', verbose_name='Вид экспертного заключения')),
            ],
            options={
                'verbose_name': 'Экспертное заключение',
                'verbose_name_plural': 'Экспертные заключения',
            },
        ),
        migrations.AddField(
            model_name='expertise',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resource', verbose_name='ЭОР'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='ums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ums', verbose_name='УМС института'),
        ),
    ]
